### ISSUE TITLE
 Introduce network namespace instances into nftlb model (Enhancement)

### ISSUE THREAD

**Issue by zhanrox2** [zevenet/nftlb#10]
At present, Farms (including tables, chains, and rules) of nftlb only work in the host's default network namespace. Is there any plan to introduce the concept of network namespace instances into nftlb , in order to build different Farms into different network namespaces, but not to run an nftlb daemon in each network namespace. @nevola

**Comment by nevola** [comment]
Yes, it is planned to be introduced early this year.

**Comment by zhanrox2** [comment]
Ok, very good, please let me know if there is new progress！

**Comment by zhanrox2** [comment]
Ok, very good, please let me know if there is new progress，thank you!
