### ISSUE TITLE
POST to /farms does not re-create missing tables and/or chains

### ISSUE THREAD

**Issue by ghost** [zevenet/nftlb#11]
Hi. In the course of integrating nftlb into my favourite Linux distribution, I implemented a reload action that POSTs the entire configuration to /farms. The intent is to be able to adjust nftlb's configuration in the least disruptive way and without having to kill and spawn nftlb again.

I am finding that this approach is not entirely reliable. Upon initially spawning nftlb with a valid configuration, it produces the necessary tables and chains. However, if one of the initially generated tables and/or chains goes missing before the next POST attempt, nftlb will report a response value of "success", but will not re-create the missing resources.

For context, here is what my reload function - part of an OpenRC runscript - does:

```sh
reload() {
	local json response

	ebegin "Reloading $RC_SVCNAME"
	# FIXME: first test temporarily de-activated for bug reporting purposes
	if false && { ! nft list tables | grep -qE ' (ip6?|netdev) nftlb$'; }; then
		# Unfortunately, a POST request is a successful no-op in the case that
		# the nftlb table has gone away. This issue needs reporting upstream.
		eerror "The nftlb table is unexpectedly missing. Restart the service instead."
	elif ! check_nftlb_config_syntax; then
		false
	elif ! json=$(do_curl -X POST -d @- < "$NFTLB_CONFIG"); then
		false
	elif ! response=$(printf %s "$json" | jshon -Q -e response -u); then
		eerror "Unexpected payload from JSON API: $json"
	elif [ "$response" != success ]; then
		eerror "Unsuccessful response code from JSON API: $response"
	fi
	eend $?
}

do_curl() {                                                                     
    curl -fsSH "Key: $NFTLB_KEY" "$@" "http://${NFTLB_HOST}:${NFTLB_PORT}/farms"
}
```

As you can see, it is quite thorough. It performs a sanity check of the configuration file before issuing a POST request. The reponse, if any, is tested as being valid JSON and containing a "response" key. Finally, the value of the key is tested as being "success". Should any of these tests fail, the function will return a non-zero exit status value (the eerror command sets $? to 1 also).

Now for a demonstration of the problem:-

```
# rc-service nftlb start
 * Starting nftlb ... [ ok ]

# nft list tables | grep nftlb
table ip nftlb

# nft delete table ip nftlb

# rc-service nftlb reload
 * Reloading nftlb ... [ ok ]

# nft list tables | grep nftlb

# rc-service nftlb restart
 * Stopping nftlb ... [ ok ]
 * Starting nftlb ... [ ok ]

# nft list tables | grep nftlb
table ip nftlb
```

What happens here is that reload action succeeds, meaning that the reponse code was "success" from nftlb. However, the table remains missing. Only a restart - which re-spawns nftlb - brings the table back.

It is a similar story with the generated chains. Taking the "filter" chain as an example:-

```
# rc-service nftlb start
 * Starting nftlb ... [ ok ]

# nft list chain ip nftlb filter >/dev/null

# nft delete chain ip nftlb filter

# rc-service nftlb reload
 * Reloading nftlb ... [ ok ]

# nft list chain ip nftlb filter >/dev/null
Error: No such file or directory; did you mean chain ‘filter-lb01’ in table ip ‘nftlb’?
list chain ip nftlb filter
                    ^^^^^^
# rc-service nftlb restart
 * Stopping nftlb ... [ ok ]
 * Starting nftlb ... [ ok ]

# nft list chain ip nftlb filter >/dev/null
```

This is surprising to me. It seems logical to assume that posting a complete, valid configuration to /farms would create any of the resources that are required by the configuration, whether they already exist or not. At the least, I would expect it not to report "success" in the JSON response if it is unable to enact the posted configuration.

It makes it impossible to really trust the API; given this issue, it is not hard to imagine that nftlb may also have a problem in switching between significantly different configurations by way of POST. From the point of view of distro integration, it means that I have to give up on the idea of dynamic reloading (for now) and rely instead on fully restarting nftlb, instead of using the API. Just to be sure.

By the way, I am using commit cd5c964. This is the configuration that I used for reporting this issue:-

```json
{
  "farms": [
    {
      "name": "lb01",
      "family": "ipv4",
      "virtual-addr": "1.2.3.4",
      "virtual-ports": "443,6595",
      "mode": "dnat",
      "protocol": "tcp",
      "scheduler": "weight",
      "state": "up",
      "backends": [
        {
          "name": "gs1",
          "ip-addr": "10.0.2.1",
          "port": "6595",
          "weight": "500",
          "mark": "0x1",
          "state": "up"
        }
      ]
    }
  ]
}
```

**Comment by nevola** [comment]
Hi @kerframil 

nftlb API can be used to configure incremental changes to the farms, so if you use the API to perform configuration changes this should be ok. But, if an object is missing, this is not going to be removed as the daemon thinks that such object has not being changed.

If this is your case, you have to DELETE first any farm object (as you're not aware of the object missing) with:

`curl -X DELETE http://<endpoint>/farms`

and then, resend your JSON configuration file.

**Comment by ghost** [comment]
Hmm, I see. So, for a reload action, perhaps I should live with this constraint and just trust that the user will not modify the state of any resources other than via the API between invocations. Regarding DELETE, there is issue #13 though.

**Comment by nevola** [comment]
The user can change the state. One farm could be set as "down" and during the POST this will be updated, but as this is an API native configuration service, you cannot delete the farms via POST.

**Comment by nevola** [comment]
In summary, the best way to do a reload would be:
DELETE /farms
and then, resend the JSON file.

I'll close this issue, if any other system is proposed, please feel free to open it again. Thanks!
