### ISSUE TITLE
Issuing DELETE to /farms destroys the entire nftables ruleset

### ISSUE THREAD

**Issue by ghost** [zevenet/nftlb#13]
Hi. As shown below, issuing a DELETE request to /farms causes nftlb to delete tables that it does not own. This was tested with commit 7a248b5.

```
# rc-service nftlb status
 * status: started

# nft list tables
table ip filter
table ip nat
table ip mangle
table ip raw
table arp filter
table ip nftlb

# curl -H "Key: $NFTLB_KEY" -X DELETE http://localhost:5555/farms
{"response": "success"}

# nft list tables | wc -l
0
```

**Comment by nevola** [comment]
Yes, currently it uses "nft flush ruleset", it can be changed by "nft flush table nftlb" in order to ensure to delete only nftlb chains and rules.

**Comment by ghost** [comment]
One problem with "nft flush table nftlb" is that it would only cover the "ip" family. I think that nftlb can also create "ip6" and "netdev" family tables too, can't it? Maybe it could use its internal state to know which families need to be iterated over.

**Comment by nevola** [comment]
Sure, it will be checked which table types are in use in order to remove it.

**Comment by ghost** [comment]
As far as I can tell, unconditionally deleting the three tables that nftlb potentially creates is a viable alternative to "flush ruleset". Therefore, I am now using [this modification](https://github.com/kerframil/nftlb/commit/f1313ad00681e0f87d310ee1ea5d96145c392355).

**Comment by ghost** [comment]
By the way, this could also be a solution for issue #14.

**Comment by nevola** [comment]
Commit applied, reopen if need any rework.
