### ISSUE TITLE
Re-spawning nftlb can insert duplicate rules

### ISSUE THREAD

**Issue by ghost** [zevenet/nftlb#14]
Hi. Unless the user specifically ensures that the tables named "nftlb" are destroyed first, nftlb may insert duplicate rules when spawned. Here is an example.

```
# rc-service nftlb start
 * Starting nftlb ... [ ok ]

# nft list chain ip nftlb filter
table ip nftlb {
        chain filter {
                type filter hook prerouting priority mangle; policy accept;
                meta mark set ct mark
                ip daddr . tcp dport vmap @filter-tcp-services
        }
}

# rc-service nftlb restart
 * Stopping nftlb ... [ ok ]
 * Starting nftlb ... [ ok ]

# nft list chain ip nftlb filter
table ip nftlb {
        chain filter {
                type filter hook prerouting priority mangle; policy accept;
                meta mark set ct mark
                ip daddr . tcp dport vmap @filter-tcp-services
                meta mark set ct mark
                ip daddr . tcp dport vmap @filter-tcp-services
        }
}
```

Using the API to post the config does not have this same problem. Anyway, it is surprising that re-spawning nftlb with the same config is not indempotent. For now, I am working around this issue by hooking the start function in my OpenRC runscript. Here is a simplified example.

```
start_pre() {
	# This is necessary because nftlb may otherwise produce duplicate nft rules.
	local family
	for family in ip ip6 netdev; do
		nft list table "$family" nftlb >/dev/null 2>&1 || continue
		nft delete table "$family" nftlb
	done
}
```

This suffices as a workaround. Still, it would be preferable for nftlb to atomically re-create the needed tables when it is started, without inserting duplicate rules - especially because said workaround interrupts load balancing services for a brief instant.

**Comment by nevola** [comment]
In the README file it's noted of this limit:

Note 2: Before executing nftlb, ensure you have empty nft rules by executing "nft flush ruleset"

But, currently we've the infrastructure needed to know if a table is created or not. I'll include it in the TODO list.

Thanks.

**Comment by ghost** [comment]
Thank you. In the meantime, I can easily ensure that the nftlb-related tables are destroyed in the course of starting.

**Comment by nevola** [comment]
Commit applied, reopen if need any rework.
