### ISSUE TITLE
nftlb dies with consumed > 0 assertion

### ISSUE THREAD

**Issue by ghost** [zevenet/nftlb#15]
Hi. While experimenting with my nftables ruleset, I found that I was able to trigger an assertion in commit f1313ad of nftlb, from the master branch. I upgraded to commit 97d46ec and found it to be the same. Here is a minimal nftables ruleset that can be used to reproduce the issue:

```
flush ruleset

table ip metrics  {
	set servers {
		type ipv4_addr
	}
	chain egress {
		type filter hook prerouting priority filter - 1; policy accept;
		iifname != "igb0" ct original daddr @servers
	}
}
```

And here is a sample nftlb configuration to go along with it:

```json
{
 "farms": [
  {
   "name": "lb01",
   "family": "ipv4",
   "virtual-addr": "1.2.3.4",
   "virtual-ports": "443,6595",
   "source-addr": "",
   "mode": "dnat",
   "protocol": "tcp",
   "scheduler": "weight",
   "sched-param": "none",
   "persistence": "none",
   "persist-ttl": "60",
   "helper": "none",
   "log": "none",
   "mark": "0x0",
   "priority": "5",
   "state": "up",
   "new-rtlimit": "0",
   "new-rtlimit-burst": "0",
   "rst-rtlimit": "0",
   "rst-rtlimit-burst": "0",
   "est-connlimit": "0",
   "tcp-strict": "off",
   "queue": "-1",
   "backends": [
    {
     "name": "s1",
     "ip-addr": "10.0.2.1",
     "port": "6595",
     "weight": "50",
     "priority": "1",
     "mark": "0x1",
     "est-connlimit": "0",
     "state": "up"
    }
   ],
   "policies": []
  }
 ]
}
```

After loading the given nftables ruleset, starting nftlb with the given nftlb configuration (or POSTing it) produces the following error before dying:

```
nftlb: netlink_delinearize.c:124: netlink_parse_concat_expr: Assertion `consumed > 0' failed.
```

When this happens, the only thing that I see logged is ```nft command exec : list table ip nftlb```. Curiously, removing the ```ct original daddr @servers``` condition from the one rule is enough to stop nftlb from crashing.

**Comment by ghost** [comment]
🤦‍♂ Well, I just realised that this is a bug that goes beyond nftlb and is probably in libnftl. Running ```nft list table ip nftlb``` produces the same assertion. I suppose there is nothing that can be done here. In any case, I shall report it upstream.

**Comment by ghost** [comment]
Filed as https://bugzilla.netfilter.org/show_bug.cgi?id=1406.

**Comment by nevola** [comment]
Thank you for reporting. The netfilter team will take care of it.
