### ISSUE TITLE
Could this software be delivered in form of deb and/or rpm package?

### ISSUE THREAD

**Issue by q2dg** [zevenet/nftlb#17]
Thanks!!

**Comment by emiliocampos-zevenet** [comment]
This package is currently created in deb package in our public apt
repository, so you only have to download and use it.

Alien binary can help you to convert to rpm but not tested, you could
experience maybe some dependency issue ...

Thanks !

**Comment by q2dg** [comment]
Sorry for the inconvenience. I'll close this issue if you don't mind, then.

However, your public apt repository isn't even mentioned in README.md, so I don't know which is its url.

**Comment by emiliocampos-zevenet** [comment]
It is true, there is no mention in the README, please refer to this article for further help about the APT repo.

https://www.zevenet.com/knowledge-base/howtos/configure-apt-repository-zevenet-community-edition/

If you need further information please let us know. Glad to help
