### ISSUE TITLE
Correct way to set backend to maintenance mode

### ISSUE THREAD

**Issue by rjasonadams** [zevenet/nftlb#18]
Hello,

We're running (latest commit) of nftlb in DSR mode with persistence of 120s. When we set a backend to "off" in an attempt to perform maintenance the traffic falls off nearly instantly. Most of our TCP connections are usually long lived (15min-1h). Is it possible to put a backend into maintenance mode and have the traffic move gradually?

**Comment by nevola** [comment]
We'll study the case and provide a solution soon. Thank you!

**Comment by rjasonadams** [comment]
Great. Thank you. Let me know if you need any additional information.

**Comment by nevola** [comment]
Hi, are you setting static session persistence or dynamic? Please share your farm configuration. Thank you!

**Comment by rjasonadams** [comment]
We're only using dynamic. Example config:
```
		{
			"name" : "vip1",
			"family" : "ipv4",
			"virtual-addr" : "10.0.0.254", "virtual-ports" : "23,80,443",
			"persistence" : "srcip ", "persist-ttl" : "300",
			"mode" : "dsr",
			"protocol" : "tcp",
			"scheduler" : "hash",
			"state" : "up",
			"backends" : [
				       { "name" : "r01","ip-addr" : "10.0.0.10", "ether-addr" : "00:01:02:03:04:10","weight" : "5","priority" : "1","state" : "up"},
				       { "name" : "r02","ip-addr" : "10.0.0.11", "ether-addr" : "00:01:02:03:04:11","weight" : "5","priority" : "1","state" : "up"},
				       { "name" : "r03","ip-addr" : "10.0.0.12", "ether-addr" : "00:01:02:03:04:12","weight" : "5","priority" : "1","state" : "up"},
			             ],
			"iface" : "eth0", "oface" : "eth0"
		}
```

**Comment by nevola** [comment]
Finally, we're going to avoid to remove the active sessions under maintenance or down backend, so you can delete current sessions via API on demand, if it's required.

I'll apply the changes in the devel branch.

Thank you.

**Comment by nevola** [comment]
Hi, I've applied the changes to avoid the session deletion after a backend down or off, but also, a new web service to delete backend sessions on-demand:

https://github.com/zevenet/nftlb/commit/fa430b497000b3e70b1d7a3d4789fe2962a75dc6
https://github.com/zevenet/nftlb/commit/b290659c24bf58e5f648aa065887708603bd52d7

Please give it a try and let me know if solves your issue.

Thanks.

**Comment by nevola** [comment]
This issue should be already fixed in the devel branch. Please test it and re-open the ticket if needed.
Thanks.
