### ISSUE TITLE
Any plans for 4\5 -tuple hashing support?

### ISSUE THREAD

**Issue by elico** [zevenet/nftlb#20]
I have seen that the LB hashing is based on ip saddr + sport but havn't seen a full tuple hashing, are you planning on adding these?

My scenario is with Squid-Cache proxy cluster in intercept mode.
The basic way it works is that the client tries to reach the internet and the connection is being redirected towards a proxy from the cluster.

Thanks,

**Comment by nevola** [comment]
Hi @elico the hash is configurable via the sched-param attribute with a blank space separator, example:

Hash with only source ip:
	"sched-param": "srcip"

Hash with source ip + source port:
	"sched-param": "srcip srcport"

Hash with source ip + source port + destination ip + destination port:
	"sched-param": "srcip srcport dstip dstport"

Also, you can try with symmetric hash with:
	"scheduler": "symhash"

Hope this helps for your use case.

**Comment by elico** [comment]
@nevola Thanks helped a lot.
