### ISSUE TITLE
Couldnt find the iface oface and respective ether-addr documentation

### ISSUE THREAD

**Issue by elico** [zevenet/nftlb#21]
I have tried my luck with the README.dm and I am kind of confused what should and if at all.
In the test file: https://github.com/zevenet/nftlb/blob/master/tests/004_dsr_ipv4_tcp_hash/input.json

there are iface and oface variables which I found some sources which helped me to grasp the concept at:
https://github.com/zevenet/nftlb/blob/master/include/farms.h#L113

how should I write the iethaddr or oethaddr? what variable to use?
I noticed that it's not required to have from a json perspective these variables in the dictionary are has the same name but maybe a different location?

Thanks,

**Comment by nevola** [comment]
Hi @elico,

iface, oface and ether addresses are not needed to be set as they're automatically calculated bu the daemon. Nevertheless, in some cases we need to force the device (for example, if the ip address is not configured in the local machine). For that reason, we force it in the tests but they're not required to be set.

**Comment by elico** [comment]
@nevola Thanks. Now it makes more sense.
It's exactly my case since the ip address is not configured on the machine.
I noticed that the mac is not needed in my tests now it's much clear to me.

Thanks!

**Comment by elico** [comment]
@nevola Can the oface and iface ether-addr name be changed to oether-addr and iether-addr to make the syntax more simple?

**Comment by nevola** [comment]
Sure!
