### ISSUE TITLE
README.md  refers to a link that replies with 404

### ISSUE THREAD

**Issue by oza4h07** [zevenet/nftlb#23]
Hello,

In README.md's How it works section, there is a link to:
[https://www.zevenet.com/knowledge-base/nftlb/](url)

This link replies with 404, when clicked over from my PC.
Best regards

**Comment by nevola** [comment]
Fixed.
https://github.com/zevenet/nftlb/commit/0119a0f4ca4549a7ee8ee8752d28e9bbc0729b48

Thank you for your report!
