### ISSUE TITLE
Unable to delete a backend of a virtual service

### ISSUE THREAD

**Issue by zhanrox** [zevenet/nftlb#4]
**1. My Lab Environment**

- Kernel：4.19.8-1
- nftables：v0.9.1
- libev：4.15-7
- libjansson：2.10-1
- libmnl：1.0.4
- libnftnl：1.1.3
- gcc：4.8.5-36

**2. Setup a new virtual service lb01**

	# vim lb01.json
	{
		"farms" : [
			{
				"name" : "lb01",
				"family" : "ipv4",
				"virtual-addr" : "200.1.1.1",
				"virtual-ports" : "8080",
				"mode" : "snat",
				"protocol" : "tcp",
				"scheduler" : "weight",
				"state" : "up",
				"backends" : [
					{
						"name" : "bck0",
						"ip-addr" : "172.16.138.202",
						"port" : "80",
						"weight" : "5",
						"mark" : "0x0000001",
						"priority" : "1",
						"state" : "up"
					},
					{
						"name" : "bck1",
						"ip-addr" : "172.16.138.203",
						"port" : "80",
						"weight" : "5",
						"mark" : "0x0000002",
						"priority" : "1",
						"state" : "up"
					}
				]
			}
		]
	}
	
	# curl -H "Key: zhanrox" -X POST http://172.16.138.201:5555/farms -d "@lb01.json"

**3. List virtual service lb01**

	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									},
									{
											"name": "bck1",
											"ip-addr": "172.16.138.203",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x2",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}

So far, everything works fine

**4. Delete a backend of a virtual service**

	# curl -H "Key: zhanrox" -X DELETE http://172.16.138.201:5555/farms/lb01/backends/bck1
	{"response": "success"}
	
	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}

As you can see, the backend bck1 has been removed from the virtual service lb01.But look at the nftables table,  the backend bck1（172.16.138.203） still exist, did not really deleted，as follows：

	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 10 map { 0-4 : 0x80000001, 5-9 : 0x80000002 }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
			ip protocol tcp ct mark 0x80000002 dnat to 172.16.138.203:80
		}
	}

What is the problem？ @nevola

**Comment by nevola** [comment]
Please try to stop the backend with _status: down_ before the deletion. I changed this code few weeks ago and probably I inserted this bug.
Thanks.

**Comment by zhanrox** [comment]
> Please try to stop the backend with _status: down_ before the deletion. I changed this code few weeks ago and probably I inserted this bug.
> Thanks.

@nevola  Thank you for your reply!  Is there an API interface that can make a backend service down ?

**Comment by nevola** [comment]
Sure, something like:

{
	"farms" : [
		{
			"name" : "lb01",
			"backends" : [
				{
					"name" : "bck1",
					"state" : "down"
				}
			]
		}
	]
}

And post it to the farm service.

**Comment by zhanrox** [comment]
@nevola  OK，It seems to work.

**1. List virtual service lb01 From nftlb&nftables**

	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									},
									{
											"name": "bck1",
											"ip-addr": "172.16.138.203",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x2",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}

	
	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 10 map { 0-4 : 0x80000001, 5-9 : 0x80000002 }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
			ip protocol tcp ct mark 0x80000002 dnat to 172.16.138.203:80
		}
	}


**2. Make the backend bck1(172.16.138.203:80) of virtual service lb01 down**

	# curl -H "Key: zhanrox" -X POST http://172.16.138.201:5555/farms -d '{"farms" : [ { "name" : "lb01", "backends" : [ { "name" : "bck1", "state" : "down" } ] } ] }'
	{"response": "success"}
	
	
	
	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									},
									{
											"name": "bck1",
											"ip-addr": "172.16.138.203",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x2",
											"est-connlimit": "0",
											"state": "down"
									}
							],
							"policies": []
					}
			]
	}
	
	
	
	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 5 map { 0-4 : 0x80000001 }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
		}
	}

It can be seen that the state of the backend bck1 in nftlb becomes down, and the relevant rules about bck1 have been removed from nftables.

**3. Delete the backend bck1 of a virtual service lb01**

	# curl -H "Key: zhanrox" -X DELETE http://172.16.138.201:5555/farms/lb01/backends/bck1
	
	
	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}
	
	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 5 map { 0-4 : 0x80000001 }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
		}
	}

It can be seen that the backend bck1 have been removed from nftlb.
What is the purpose of this design, can it be deleted directly?

**Comment by nevola** [comment]
It should be possible. This is just a bug I introduced recently. I'll fix it very soon, thank you for your report!

**Comment by zhanrox** [comment]
@nevola  OK, I get it ,  Thank you!
