### ISSUE TITLE
Can nftlb run in daemon mode?

### ISSUE THREAD

**Issue by zhanrox** [zevenet/nftlb#5]
Hi，@nevola   Can nftlb run in daemon mode?
I have checked the nftlb run parameters and found no related parameters，as follows:
	
	# nftlb -h
	nftlb, nftables load balancer - Version 0.5
	(c) 2018 by Laura Garcia <laura.garcia@zevenet.com>
	Usage: nftlb
	[ -h | --help ]			Show this help
	[ -l <LEVEL> | --log <LEVEL> ]	Set the syslog level
	[ -c <FILE> | --config <FILE> ]	Launch with the given configuration file
	[ -k <KEY> | --key <KEY> ]		Set the authentication key, otherwise it'll be generated
	[ -e | --exit ]			Don't execute the server
	[ -6 | --ipv6 ]			Enable IPv6 listening port
	[ -H <HOST> | --host <HOST> ]		Set the host for the listening port
	[ -P <PORT> | --port <PORT> ]		Set the port for the listening port

Currently, I use the following command to run nftlb:

	# nftlb -l info -k zhanrox -H 172.16.138.201 -P 5555 > /dev/null &

**Comment by nevola** [comment]
Hi, it could be included, sure!
