### ISSUE TITLE
The API interface of clean up all virtual services has a bug 

### ISSUE THREAD

**Issue by zhanrox** [zevenet/nftlb#6]
**1. My Lab Environment**

- nftlb：v0.5
- Kernel：4.19.8-1
- nftables：v0.9.1
- libev：4.15-7
- libjansson：2.10-1
- libmnl：1.0.4
- libnftnl：1.1.3
- gcc：4.8.5-36

**2. Before cleaning up all virtual services**

	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									},
									{
											"name": "bck1",
											"ip-addr": "172.16.138.203",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x2",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}
	
	
	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 10 map { 0-4 : 0x80000001, 5-9 : 0x80000002 }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
			ip protocol tcp ct mark 0x80000002 dnat to 172.16.138.203:80
		}
	}

**3. Cleaned all virtual services**

	# curl -H "Key: zhanrox" -X DELETE http://172.16.138.201:5555/farms
	{"response": "success"}
	
	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": []
	}
	
	# nft list tables
	#

It can be found that nftables has been emptied after executing the API interface.

**4.Setup a new virtual service**

	# vim lb01.json
	{
		"farms" : [
			{
				"name" : "lb01",
				"family" : "ipv4",
				"virtual-addr" : "200.1.1.1",
				"virtual-ports" : "8080",
				"mode" : "snat",
				"protocol" : "tcp",
				"scheduler" : "weight",
				"state" : "up",
				"backends" : [
					{
						"name" : "bck0",
						"ip-addr" : "172.16.138.202",
						"port" : "80",
						"weight" : "5",
						"mark" : "0x0000001",
						"priority" : "1",
						"state" : "up"
					},
					{
						"name" : "bck1",
						"ip-addr" : "172.16.138.203",
						"port" : "80",
						"weight" : "5",
						"mark" : "0x0000002",
						"priority" : "1",
						"state" : "up"
					}
				]
			}
		]
	}
	
	# curl -H "Key: zhanrox" -X POST http://172.16.138.201:5555/farms -d "@lb01.json"
	{"response": "success"}
	
	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "none",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck0",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									},
									{
											"name": "bck1",
											"ip-addr": "172.16.138.203",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x2",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}
	
	# nft list tables
	# nft list ruleset
	#

It can be found that although a new virtual service is created, but it is only defined in nftlb, nftables is still empty. @nevola

**Comment by nevola** [comment]
I'm investigating this issue.
Thanks for your report.
