### ISSUE TITLE
The API interface of Delete virtual service has a bug

### ISSUE THREAD

**Issue by zhanrox** [zevenet/nftlb#8]
### 1. My Lab Environment

- nftlb：Master
- Kernel：4.19.8-1
- nftables：v0.9.1
- libev：4.15-7
- libjansson：2.10-1
- libmnl：1.0.4
- libnftnl：1.1.3
- gcc：4.8.5-36

### 2. Before cleaning up the virtual services

	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": [
					{
							"name": "lb01",
							"family": "ipv4",
							"virtual-addr": "200.1.1.1",
							"virtual-ports": "8080",
							"source-addr": "",
							"mode": "snat",
							"protocol": "tcp",
							"scheduler": "weight",
							"sched-param": "none",
							"persistence": "srcip srcport ",
							"persist-ttl": "60",
							"helper": "none",
							"log": "none",
							"mark": "0x0",
							"priority": "1",
							"state": "up",
							"new-rtlimit": "0",
							"new-rtlimit-burst": "0",
							"rst-rtlimit": "0",
							"rst-rtlimit-burst": "0",
							"est-connlimit": "0",
							"tcp-strict": "off",
							"queue": "-1",
							"backends": [
									{
											"name": "bck1",
											"ip-addr": "172.16.138.202",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x1",
											"est-connlimit": "0",
											"state": "up"
									},
									{
											"name": "bck2",
											"ip-addr": "172.16.138.203",
											"port": "80",
											"weight": "5",
											"priority": "1",
											"mark": "0x2",
											"est-connlimit": "0",
											"state": "up"
									}
							],
							"policies": []
					}
			]
	}

	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map tcp-services-back-m {
			type mark : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		map persist-lb01 {
			type ipv4_addr . inet_service : mark
			size 65535
			timeout 1m
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
			snat to ct mark map @tcp-services-back-m
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 10 map { 0-4 : 0x80000001, 5-9 : 0x80000002 }
			update @persist-lb01 { ip saddr . tcp sport : ct mark }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
			ip protocol tcp ct mark 0x80000002 dnat to 172.16.138.203:80
		}
	}

### 3. Delete the virtual service

	#  curl -H "Key: zhanrox" -X DELETE http://172.16.138.201:5555/farms/lb01
	{"response": "success"}

	# curl -H "Key: zhanrox" http://172.16.138.201:5555/farms
	{
			"farms": []
	}

For nftlb，it can be found that the virtual service lb01 has been deleted success after executing the API interface.

	# nft list table nftlb
	table ip nftlb {
		map nat-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto nat-lb01 }
		}
	
		map tcp-services-back {
			type ipv4_addr . inet_service : ipv4_addr
		}
	
		map tcp-services-back-m {
			type mark : ipv4_addr
		}
	
		map filter-tcp-services {
			type ipv4_addr . inet_service : verdict
			elements = { 200.1.1.1 . 8080 : goto filter-lb01 }
		}
	
		map persist-lb01 {
			type ipv4_addr . inet_service : mark
			size 65535
			timeout 1m
		}
	
		chain prerouting {
			type nat hook prerouting priority filter; policy accept;
			ip daddr . tcp dport vmap @nat-tcp-services
		}
	
		chain postrouting {
			type nat hook postrouting priority srcnat; policy accept;
			ct mark 0x80000000/1 masquerade
			snat to ip daddr . tcp dport map @tcp-services-back
			snat to ct mark map @tcp-services-back-m
		}
	
		chain filter {
			type filter hook prerouting priority mangle; policy accept;
			meta mark set ct mark
			ip daddr . tcp dport vmap @filter-tcp-services
		}
	
		chain filter-lb01 {
			ct mark set numgen random mod 10 map { 0-4 : 0x80000001, 5-9 : 0x80000002 }
			update @persist-lb01 { ip saddr . tcp sport : ct mark }
		}
	
		chain nat-lb01 {
			ip protocol tcp ct mark 0x80000001 dnat to 172.16.138.202:80
			ip protocol tcp ct mark 0x80000002 dnat to 172.16.138.203:80
		}
	}

But for nftables, the content still exists and is not updated synchronously. @nevola

**Comment by nevola** [comment]
@zhanrox I'm not able to reproduce it, could you try with the current git code?
Thanks!

**Comment by nevola** [comment]
@zhanrox can you check any error in the syslog? I've just realized that you're using a 4.19 kernel and you would require at least a 4.19.38 that includes some patches to fix objects removal in nftables.
Please let me know, thanks.

**Comment by nevola** [comment]
Hi! did you have the chance to try out with a kernel >= 4.19.38 ?
Thanks.

**Comment by nevola** [comment]
Please reopen the case if you can reproduce the issue with a kernel >= 4.19.38.
Thanks.

**Comment by zhanrox2** [comment]
Sorry, I have been busy recently. Upgrade the kernel to 4.19.38 as you meant, the test is ok, thank you! @nevola
